spring:
  datasource:
    url: jdbc:mysql://localhost:3307/dogsdb
    username: app
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
