spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dogsdb
    username: app
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logs:
  api:
    url: http://localhost:8081
